services:
  printix-sftp-connector:
    build: .
    image: printix-sftp-connector:latest
    container_name: printix-sftp-connector
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"

    environment:
      PORT: "${PORT:-3000}"
      LOG_STACK_TRACES: "${LOG_STACK_TRACES:-false}"
      PROFILE_1_SECRET_KEYS: "${PROFILE_1_SECRET_KEYS:-}"
      PROFILE_1_TOKENS: "${PROFILE_1_TOKENS:-}"
      PROFILE_1_SFTP_HOST: "${PROFILE_1_SFTP_HOST}"
      PROFILE_1_SFTP_PORT: "${PROFILE_1_SFTP_PORT:-22}"
      PROFILE_1_SFTP_USER: "${PROFILE_1_SFTP_USER}"
      PROFILE_1_SFTP_PASSWORD: "${PROFILE_1_SFTP_PASSWORD:-}"
      PROFILE_1_SFTP_KEY_PATH: "${PROFILE_1_SFTP_KEY_PATH:-}"
      PROFILE_1_SFTP_KEY_PASSPHRASE: "${PROFILE_1_SFTP_KEY_PASSPHRASE:-}"
      PROFILE_1_SFTP_HOST_FINGERPRINT: "${PROFILE_1_SFTP_HOST_FINGERPRINT:-}"
      PROFILE_1_SFTP_REMOTE_DIR: "${PROFILE_1_SFTP_REMOTE_DIR:-/uploads/printix/invoices}"
      PROFILE_2_SECRET_KEYS: "${PROFILE_2_SECRET_KEYS:-}"
      PROFILE_2_TOKENS: "${PROFILE_2_TOKENS:-}"
      PROFILE_2_SFTP_HOST: "${PROFILE_2_SFTP_HOST:-}"
      PROFILE_2_SFTP_PORT: "${PROFILE_2_SFTP_PORT:-22}"
      PROFILE_2_SFTP_USER: "${PROFILE_2_SFTP_USER:-}"
      PROFILE_2_SFTP_PASSWORD: "${PROFILE_2_SFTP_PASSWORD:-}"
      PROFILE_2_SFTP_KEY_PATH: "${PROFILE_2_SFTP_KEY_PATH:-}"
      PROFILE_2_SFTP_KEY_PASSPHRASE: "${PROFILE_2_SFTP_KEY_PASSPHRASE:-}"
      PROFILE_2_SFTP_HOST_FINGERPRINT: "${PROFILE_2_SFTP_HOST_FINGERPRINT:-}"
      PROFILE_2_SFTP_REMOTE_DIR: "${PROFILE_2_SFTP_REMOTE_DIR:-/uploads/printix/general/{year}/{month}/{day}}"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
